-- Generated using GM2MC ( GTA:SA Models To MTA:SA Converter ) by SoRa

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'ak47.txd' ) 
engineImportTXD( txd, 355 ) 
dff = engineLoadDFF('ak47.dff', 355) 
engineReplaceModel( dff, 355 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'bat.txd' ) 
engineImportTXD( txd, 334 ) 
dff = engineLoadDFF('bat.dff', 334) 
engineReplaceModel( dff, 334 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'silenced.txd' ) 
engineImportTXD( txd, 347) 
dff = engineLoadDFF('silenced.dff', 347) 
engineReplaceModel( dff, 347 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'sniper.txd' ) 
engineImportTXD( txd, 358 ) 
dff = engineLoadDFF('sniper.dff', 358) 
engineReplaceModel( dff, 358 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'm4.txd' ) 
engineImportTXD( txd, 356 ) 
dff = engineLoadDFF('m4.dff', 356) 
engineReplaceModel( dff, 356 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'desert_eagle.txd' ) 
engineImportTXD( txd, 348 ) 
dff = engineLoadDFF('desert_eagle.dff', 356) 
engineReplaceModel( dff, 348 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'sawnoff.txd' ) 
engineImportTXD( txd, 350 ) 
dff = engineLoadDFF('sawnoff.dff', 350) 
engineReplaceModel( dff, 350 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'shotgspa.txd' ) 
engineImportTXD( txd, 351 ) 
dff = engineLoadDFF('shotgspa.dff', 351) 
engineReplaceModel( dff, 351 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'chromegun.txd' ) 
engineImportTXD( txd, 349 ) 
dff = engineLoadDFF('chromegun.dff', 349) 
engineReplaceModel( dff, 349 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'mp5lng.txd' ) 
engineImportTXD( txd, 353 ) 
dff = engineLoadDFF('mp5lng.dff', 353) 
engineReplaceModel( dff, 353 )
end)

addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'colt45.txd' ) 
engineImportTXD( txd, 346 ) 
dff = engineLoadDFF('colt45.dff', 346) 
engineReplaceModel( dff, 346 )
end)



