addEvent("sendMessageToClient",true)
addEventHandler("sendMessageToClient",root,function(player,msg,hex)
        outputChatBox(hex..getPlayerName(player):gsub("_"," ")..": "..msg,255,255,255,true)
end)
addEvent("sendAdminChatToEveryone",true)
addEventHandler("sendAdminChatToEveryone",root,function(player,msg)
    outputChatBox("[#e35f23AdminChat#ffffff] "..exports["sos_admin"]:GetAdminSyntax(player).."#ffffff: " ..msg, 255, 255, 255,true)
end)
addEvent("sendAdminSChatToEveryone",true)
addEventHandler("sendAdminSChatToEveryone",root,function(player,msg)
    outputChatBox("[#10b5b0AdminSegéd - Chat#ffffff] "..exports["sos_admin"]:GetAdminSyntax(player).."#ffffff: " ..msg, 255, 255, 255,true)
end)